# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\"D\n\x10InventoryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x1f\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\r.BookCategory\"!\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\")\n\x11InventoryResponse\x12\x14\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x05.Book*?\n\x0c\x42ookCategory\x12\x0b\n\x07MYSTERY\x10\x00\x12\x13\n\x0fSCIENCE_FICTION\x10\x01\x12\r\n\tSELF_HELP\x10\x02\x32\x44\n\x0eInventoryBooks\x12\x32\n\tInventory\x12\x11.InventoryRequest\x1a\x12.InventoryResponseb\x06proto3')

_BOOKCATEGORY = DESCRIPTOR.enum_types_by_name['BookCategory']
BookCategory = enum_type_wrapper.EnumTypeWrapper(_BOOKCATEGORY)
MYSTERY = 0
SCIENCE_FICTION = 1
SELF_HELP = 2


_INVENTORYREQUEST = DESCRIPTOR.message_types_by_name['InventoryRequest']
_BOOK = DESCRIPTOR.message_types_by_name['Book']
_INVENTORYRESPONSE = DESCRIPTOR.message_types_by_name['InventoryResponse']
InventoryRequest = _reflection.GeneratedProtocolMessageType('InventoryRequest', (_message.Message,), {
  'DESCRIPTOR' : _INVENTORYREQUEST,
  '__module__' : 'inventory_pb2'
  # @@protoc_insertion_point(class_scope:InventoryRequest)
  })
_sym_db.RegisterMessage(InventoryRequest)

Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), {
  'DESCRIPTOR' : _BOOK,
  '__module__' : 'inventory_pb2'
  # @@protoc_insertion_point(class_scope:Book)
  })
_sym_db.RegisterMessage(Book)

InventoryResponse = _reflection.GeneratedProtocolMessageType('InventoryResponse', (_message.Message,), {
  'DESCRIPTOR' : _INVENTORYRESPONSE,
  '__module__' : 'inventory_pb2'
  # @@protoc_insertion_point(class_scope:InventoryResponse)
  })
_sym_db.RegisterMessage(InventoryResponse)

_INVENTORYBOOKS = DESCRIPTOR.services_by_name['InventoryBooks']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOKCATEGORY._serialized_start=167
  _BOOKCATEGORY._serialized_end=230
  _INVENTORYREQUEST._serialized_start=19
  _INVENTORYREQUEST._serialized_end=87
  _BOOK._serialized_start=89
  _BOOK._serialized_end=122
  _INVENTORYRESPONSE._serialized_start=124
  _INVENTORYRESPONSE._serialized_end=165
  _INVENTORYBOOKS._serialized_start=232
  _INVENTORYBOOKS._serialized_end=300
# @@protoc_insertion_point(module_scope)
