# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import inventory_pb2 as inventory__pb2


class InventoryBooksStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Inventory = channel.unary_unary(
                '/InventoryBooks/Inventory',
                request_serializer=inventory__pb2.InventoryRequest.SerializeToString,
                response_deserializer=inventory__pb2.InventoryResponse.FromString,
                )


class InventoryBooksServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Inventory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryBooksServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Inventory': grpc.unary_unary_rpc_method_handler(
                    servicer.Inventory,
                    request_deserializer=inventory__pb2.InventoryRequest.FromString,
                    response_serializer=inventory__pb2.InventoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'InventoryBooks', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InventoryBooks(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Inventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/InventoryBooks/Inventory',
            inventory__pb2.InventoryRequest.SerializeToString,
            inventory__pb2.InventoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
